### ISSUE TITLE
SVG emptied on sanitize

### ISSUE THREAD

**Issue by AndrassGray** [darylldoyle/svg-sanitizer#37] opened 2019-12-09 08:01 UTC
So I have an SVG file created as "Export as" in Photoshop CC 2015. Running it through the sanitizer gives the following:

![image](https://user-images.githubusercontent.com/30862808/70417825-5eee1580-1a62-11ea-9b4b-e4fe54401bec.png)

Is there anything I could do to catch this ?

Thanks a ton,
Andrass

**Comment by darylldoyle** [comment] 2019-12-09 08:55
Hi Andrass,

It's hard to say why the sanitiser would be stripping this file without seeing the full thing. Is there any chance you can post it, or send it to me in an email to daryll@enshrined.co.uk so that I can run it through locally and debug?

From what I can see, it should pass validation, but it's possible I had an old version up on the smoke test 😬

**Comment by darylldoyle** [comment] 2019-12-09 09:22
Hi @AndrassGray,

Thanks for sending the SVG over. I've seen what the issue is now. You're using `data:img/png` but currently the sanitiser only allows `data:image/png`. If you change it to that for a second, it should work. I'll get `data:img/` added to the sanitiser to stop this happening again also!

**Comment by darylldoyle** [comment] 2019-12-09 09:27
Closed in 19e85021505b29f3055c1f57a620ee4aa5c24113

**Closed by darylldoyle** 2019-12-09 09:27 UTC
Labels: question

**Comment by AndrassGray** [comment] 2019-12-09 09:36
Cool thing! Thanks a ton, Daryll !
